# config.py
"""Configuration file for Pattern V3 System"""

class Config:
    # ===== LIQUIDATION INTELLIGENCE SETTINGS =====
    SM_LIQUIDATION_VALUE_THRESHOLD = 100000
    SM_LIQUIDATION_LOOKBACK_MINUTES = 60
    SM_LIQUIDATION_CLUSTER_PERCENT = 0.01
    SM_CASCADE_RISK_THRESHOLD = 0.5
    
    # ===== LIQUIDITY SETTINGS =====
    SM_SWEEP_STRENGTH_THRESHOLD = 0.6
    SM_ENABLE_INDUCEMENT_DETECTION = True
    SM_ENABLE_SWEEP_FAILURE_DETECTION = True
    
    # ===== MARKET STRUCTURE SETTINGS =====
    SM_MARKET_STRUCTURE_LOOKBACK = 100
    
    # ===== VOLUME SETTINGS =====
    SM_VOLUME_SPIKE_THRESHOLD = 1.5
    SM_VOLUME_TREND_PERIOD = 20
    
    # ===== LOGGING =====
    LOG_LEVEL = "INFO"
    LOG_FILE = "pattern_v3.log"
    
    # ===== PATTERN DETECTION =====
    MIN_SWINGS_FOR_PATTERN = 5
    MAX_PATTERN_AGE_BARS = 50
    MIN_PATTERN_QUALITY = 0.3